---

- name: Remove wpasupplicant
  apt:
    name: wpasupplicant
    state: absent
    autoremove: yes
    purge: yes

- name: Remove bluetooth
  apt:
    name: bluez
    state: absent
    autoremove: yes
    purge: yes

- name: Remove bluez
  apt:
    name: bluez
    state: absent
    autoremove: yes
    purge: yes

- name: Remove apparmor
  apt:
    name: apparmor
    state: absent
    autoremove: yes
    purge: yes
    
- name: Remove rsyslog
  apt:
    name: rsyslog
    state: absent
    autoremove: yes
    purge: yes

- name: Remove powertop
  apt:
    name: powertop
    state: absent
    autoremove: yes
    purge: yes

- name: Remove iw
  apt:
    name: iw
    state: absent
    autoremove: yes
    purge: yes

- name: Remove pcscd
  apt:
    name: pcscd
    state: absent
    autoremove: yes
    purge: yes

- name: Remove task-laptop
  apt:
    name: task-laptop
    state: absent
    autoremove: yes
    purge: yes

- name: Remove tasksel
  apt:
    name: tasksel
    state: absent
    autoremove: yes
    purge: yes
